"""Create pgrastertime table

Revision ID: b00bcfe043ae
Revises:
Create Date: 2018-11-16 13:26:05.652461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b00bcfe043ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pgrastertime',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('tile_id', sa.BigInteger(), nullable=False),
        sa.Column('raster', geoalchemy2.types.Raster(), nullable=False),
        sa.Column('resolution', sa.Float(), nullable=False),
        sa.Column('filename', sa.UnicodeText(), nullable=True),
        sa.Column('sys_period', postgresql.TSTZRANGE(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgrastertime')
    # ### end Alembic commands ###
